### ISSUE TITLE
404 error for /wppus-update-api

### ISSUE THREAD

**Issue by jimboc100** [froger-me/wp-packages-update-server#10]
I am getting a 404 for /wppus-update-api
more specifically,
https://domain/wppus-update-api/?action=get_metadata&package_id=pkg-name&installed_version=0.9&php=7.0.25-0ubuntu0.16.04.1&locale=en_US&checking_for_updates=1&update_type=Plugin

I have a fresh WP install with only the WP Plugin Update Server plugin installed.
WP 5.0.3
Package is hosted in BitBucket private repository.

Is there something I am missing?

Extra info:
RE: BitBucket--I set up the consumer as the instructions said. It pulled the "prime" fine, but the WP list of packages still shows that first version even though the download link gets a newer version. Wondering if these issues may be related.

**Comment by froger-me** [comment]
Hello @jimboc100 !

Could you please
- reset the permalinks
- delete the package from the server
... and check if the issue still happens when visiting the API url without priming the package? (A request for update should download the package from the repository automatically anyway)

**Comment by froger-me** [comment]
No info, closing
