### ISSUE TITLE
Little confused and seeking help...

### ISSUE THREAD

**Issue by oleteacher** [froger-me/wp-packages-update-server#12]
Stumbled across your plugin in search engine and see it was removed from WP repository.

I do not see a plugin in package? Not sure how to proceed with the files that are in the package?

Please forgive my lack of knowledge on the way to obtain the plugin:) Like to use it in a classroom project.

Thanks!

**Comment by froger-me** [comment]
@oleteacher I am very sorry for the late reply - life got in the way, excuses, excuses... My apologies.
I uploaded the plugin here today for new users, and if it can still be of use for your need, I would be glad if you would still consider using it.

Cheers!

**Comment by oleteacher** [comment]
@froger-me Thank you! Totally understand "life got in the way". Funny how that can take up all of ones time:)

I will give the plugin a try, looks fantastic.
