### ISSUE TITLE
request.log missing

### ISSUE THREAD

**Issue by gmatta01** [froger-me/wp-packages-update-server#16]
In main package, request.log records all logs of requests. But folder seems empty. 
Known issue?

**Comment by froger-me** [comment]
Hello @gangesh !
The empty directory upon install is normal.
When a request for update is successfully made, the logs folder will automatically be filled with two files:
* `.htaccess` protecting the log file from intrusions
* `request.log` containing the logs of requests

The content of the `.htaccess` file will look like:
```
Order deny,allow
Deny from all
```

Each line of `request.log` will look like:
```
[timestamp] IP_address	action	slug	installed_version	wordpress_version	site_url	query_string
```

If you have been using the plugin and the folder is empty, you may need to check you server logs and make sure your WordPress installation files and directories have the right permissions as described [here](https://stackoverflow.com/questions/18352682/correct-file-permissions-for-wordpress).

**Comment by gmatta01** [comment]
@froger-me I found it in wppus directory. Solved!
