### ISSUE TITLE
Integrate with EDD Software Licensing

### ISSUE THREAD

**Issue by mohammadr3z** [froger-me/wp-packages-update-server#21]
Hi
Can this service automatically sync with EDD Software Licensing and receive license codes?

Thanks for the wonderful work

**Comment by froger-me** [comment]
With custom development, it can - at least from the WP Plugin Update Server point of view, as all the classes can be overwritten in a custom plugin, or using the documented functions, actions and filters.
Then it's just a matter of integrating with EDD - I don't know what actions or filters they have documented, so it's up to the developer of the integration.
