### ISSUE TITLE
curl error: cant resolve host

### ISSUE THREAD

**Issue by Tobias-Keller** [froger-me/wp-packages-update-server#22]
Getting this error on the "Update Page" and cant find Plugin on the details page:

`Warning: The URL https://myhost.de/wppus-update-api/?action=get_metadata&package_id=woocommerce_random_products&installed_version=0.1.3&php=7.2.31-1+ubuntu16.04.1+deb.sury.org+1&locale=de_DE&checking_for_updates=1&update_type=Plugin does not point to a valid metadata file. WP HTTP Error: cURL error 6: Could not resolve host: myhost.de in /var/www/vhosts/myhost.de/myhost.de/wp-content/plugins/woocommerce_random_products/lib/plugin-update-checker/Puc/v4p9/UpdateChecker.php on line 408`

if i open the link in browser i can get the expected json.
any solution for this problem?

**Comment by froger-me** [comment]
Hello,

Thank you for the interest in WPPUS. As indicated in the README.md file:

> **this plugin is a personal project, receiving payment for its maintenance does not fit into my schedule, and I do not plan to spend extensive amount of time maintaining it except for obvious bugs.**

I will leave the issue open in case other users or yourself are willing to provide guidance and contribute, but I won't be available to be involved.

Thank you for your understanding.

**Comment by froger-me** [comment]
Closing - no support for specific network issues
