### ISSUE TITLE
It's trying to download from the plugin intsall directory site rather than the update server 

### ISSUE THREAD

**Issue by andymoyle** [froger-me/wp-packages-update-server#23]
I've installed your plugin at www.themoyles.co.uk and have added an update.
Just testing from localhost/themoyles

Added the lib directory from the dummy-plugin to my plugin with this code...
```
require_once plugin_dir_path( __FILE__ ) . 'lib/wp-package-updater/class-wp-package-updater.php';

$parents_evening_updater = new WP_Package_Updater(
  'https://www.themoyles.co.uk',
  wp_normalize_path( __FILE__ ),
  wp_normalize_path( plugin_dir_path( __FILE__ ) )
);
```

and I get this...
Downloading update from https://localhost/moyles/wp-update-server/?action=download&token=8ec7628dfcbb4ed6&package_id=###### which gives an error

Rather than trying to download from www.themoyles.co.uk it's trying from my home server!

What have I done wrong?!

**Comment by froger-me** [comment]
Hi @andymoyle ,

Thank you for the interest in WPPUS. As indicated in the README.md file:

> **this plugin is a personal project, receiving payment for its maintenance does not fit into my schedule, and I do not plan to spend extensive amount of time maintaining it except for obvious bugs.**

I will leave the issue open in case other users or yourself are willing to provide guidance and contribute, but I won't be available to be involved.

Thank you for your understanding.

**Comment by froger-me** [comment]
CLosing - no support for localhost
