### ISSUE TITLE
Integration with plugins software-license-manager

### ISSUE THREAD

**Issue by ali110309** [froger-me/wp-packages-update-server#25]
Hello
I hope you are well
I use the software-license-manager plugin to license my plugins and templates so that licenses are created and activated automatically.
Is it possible to integrate the license section in your plugin with this plugin so that a license can be created automatically?
In general, what is your solution for creating automatic licenses for our plugins? So that the user can get and activate the license by purchasing the plugin from my site and then can receive the updates?
My site store is implemented with WooCommerce.
tanks

**Comment by ali110309** [comment]
Hello
I hope you are well.
please guide me.
@froger-me

**Comment by froger-me** [comment]
Hi @ali110309  ,

Thank you for the interest in WPPUS. As indicated in the README.md file:

> **this plugin is a personal project, receiving payment for its maintenance does not fit into my schedule, and I do not plan to spend extensive amount of time maintaining it except for obvious bugs.**

I will leave the issue open in case other users or yourself are willing to provide guidance and contribute, but I won't be available to be involved.

Thank you for your understanding.

**Comment by gmatta01** [comment]
@ali110309 Did you manage to solve this?

**Comment by gmatta01** [comment]
@ali110309 This seems to be a good start. 
https://github.com/rwsite/wc-plugin-update-server

**Comment by kevinjavitz** [comment]
@gangesh thanks for the link

**Comment by froger-me** [comment]
Closing - help has been given and dev has started again
