### ISSUE TITLE
Issue "Unexpected Error! The query to retrieve the license data returned a malformed response."

### ISSUE THREAD

**Issue by JackobStuard** [froger-me/wp-packages-update-server#26]
Hi

I read multi times guide and i setup correctly default "Dummy" plugin but for some reasons I am getting error: "Unexpected Error! The query to retrieve the license data returned a malformed response." 

Can you pls try to help me?

**Comment by tomhung** [comment]
I get the same error when trying to authorize the token from a dummy-plugin

**Comment by pmkrawczyk** [comment]
Hi All, I'm getting the same error, fresh installation of both server and plugin on the latest WP version (also freshly installed). Any tip much appreciated!

**Comment by pmkrawczyk** [comment]
Update: after resetting permalinks a few times the server started working! I have a feeling that at least in my case disabling and then re-enabling permalink tags did the trick.

To reset permalinks, go to WP settings > Permalinks, then disable the all active tags, click save, then re-enable the tags in the same order as they were before, then click save again
