### ISSUE TITLE
Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by rameezwp** [froger-me/wp-packages-update-server#27]
I received this email from GitHub,

> On {DATE} at 19:04 (UTC) your personal access token (TOKEN_NAME) using WordPress/5.4.5; {SITE_URL} was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> https://api.github.com/repositories/204429255/zipball/master
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
> 
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Is there any way to resolve it?

**Comment by github-dixit** [comment]
I just submit a pull request to solve this issue

**Comment by hugoderre** [comment]
Pull request has been accepted, this issue should be solved now
