### ISSUE TITLE
Licenses need domain to manage

### ISSUE THREAD

**Issue by Alireza-Ghavabesh** [froger-me/wp-packages-update-server#28]
hi
Licenses need domain to manage, can add domain example.com to my License in Licenses page ?

how to fill allowed_domains array ?

**Packages licensing**: Prevent plugins and themes installed on remote WordPress installation from being updated without a valid license. Licenses are generated automatically by default and the values are unguessable (it is recommended to keep the default). When checking the validity of licenses an extra license signature is also checked to prevent the use of a license on more than the configured allowed domains.

how to use this ?

**Comment by froger-me** [comment]
Once a user activates the plugin on their website, the domain is then recorded on your WPPUS, and the database of the user contains an encrypted flag allowing to indentify the website based on the domain.
During updates, WPPUS encrypts the recorded information and checks it against the encrypted flag, and allows update only if the values match.
