### ISSUE TITLE
Possible incorrect use of the function **date_i18n**

### ISSUE THREAD

**Issue by mbsouth** [froger-me/wp-packages-update-server#29]
**WP Plugin Update Server Version: 1.4.14**
**WP Version: 5.8**

Possible incorrect use of the function **date_i18n** in `
wp-plugin-update-server/wp-plugin-update-server/integration-examples/dummy-theme/lib/wp-package-updater/
` on line 445

_**Expected behavior:**_ 
Outputs a message on WP Admin Dashboard that a license has expired. This message should include the **expiration** date.

_**Actual behavior:**_ 
Outputs the current date of the day instead of the **expiration** date.

The use of **date_i18n** in /wp-package-updater/class-wp-package-updater.php on line 445:

`date_i18n( get_option( 'date_format' ), $license_data->date_expiry )`

is incorrect. According to WP code reference, the second parameter can´t be a date (string) but only int|bool: 
```
date_i18n( 
    string $format, 
    int|bool $timestamp_with_offset = false, 
    bool $gmt = false )
```

_**Possible solution:**_
445: `date_format( date_create( $license_data->date_expiry ), get_option( 'date_format' ) )`
shows the correct expiration date.

**Comment by froger-me** [comment]
Thanks for the contribution, merged with your repo!
https://github.com/froger-me/wp-plugin-update-server/pull/38
