### ISSUE TITLE
Packages assets - Banners and Icons

### ISSUE THREAD

**Issue by jaromirjagr** [froger-me/wp-packages-update-server#31]
Hello, 

How to use banners and icons?

Thanks a lot for help.

**Comment by jonkrauss** [comment]
In the plugin header add fields for BannerHigh, BannerLow, Icon1x, and Icon 2x.
https://developer.wordpress.org/plugins/plugin-basics/header-requirements/
/**
 * Plugin Name:   (your-plugin-name)
 * Icon1x: (your-image)
 * Icon2x: (your-image)
 * BannerHigh: (your-image)
 * BannerLow: (your-image)
 **/
