### ISSUE TITLE
Is it possible to remove the yellow notice after activating the license?

### ISSUE THREAD

**Issue by slimanehma** [froger-me/wp-packages-update-server#35]
Is there a way to hide the box and license notification after the customer activates a valid license?

**Comment by mbsouth** [comment]
Do you mean the yellow box inside the WP Plugin page (admin dashboard)?

**Comment by froger-me** [comment]
If you are talking about the [wp-package-updater library](https://github.com/froger-me/wp-plugin-update-server/tree/master/wp-plugin-update-server/integration-examples/dummy-plugin/lib/wp-package-updater), it is possible - you can override this library entirely, these are only examples provided for convenience.
