### ISSUE TITLE
 Public API Authentication Key

### ISSUE THREAD

**Issue by slimanehma** [froger-me/wp-packages-update-server#36]
* - Public API Authentication Key   => The Public API Authentication Key in the "Licenses" tab of WP Plugin Update Server

I can't find the Public API Authentication Key in the license settings
Where can I get it to add it to the functions file?

**Comment by froger-me** [comment]
There is no [Public API Authentication key](https://github.com/froger-me/wp-plugin-update-server/blob/master/licenses.md#public-api) ; this is a mistake in the comments of functions.php
