### ISSUE TITLE
 PHP 8.2 compatible version

### ISSUE THREAD

**Issue by mbsouth** [froger-me/wp-packages-update-server#37]
I forked this wonderful repro. 
A PHP 8.2(.4) compatible version including Puc v5p1(master) and WPUS 2.0.1(master) [is available for testing](https://github.com/mbsouth/wp-plugin-update-server).
If there are no contradictions, I will create a pull request.

**Using a remote repository** is tested with GitHub (but GitLab and BitBucket).

https://github.com/mbsouth/wp-plugin-update-server/releases/tag/v1.4.16-beta.1

**Comment by froger-me** [comment]
Thank you for the contribution, merged!
