### ISSUE TITLE
Uncaught ReferenceError: Wppus is not defined

### ISSUE THREAD

**Issue by ElementMedia** [froger-me/wp-packages-update-server#39]
I get a Uncaught ReferenceError: Wppus is not defined error when I try and click the "Get remote package" button from the "Prime a package using a Remote Repository (recommended)" option.

Maybe related: When on the Licenses tab I click on "Add License", nothing happens.

**Comment by froger-me** [comment]
Hi, thank you for the heads up, it will be fixed ASAP!
It seems you are using code from the `master` branch. So far none of the 2.x version has been released: for stable (but soon-to-be incompatible) version, please see https://github.com/froger-me/wp-packages-update-server/releases

Thanks again for the heads up, it's now in the bakcklog!

**Comment by ElementMedia** [comment]
Thanks for your quick response. I was indeed using the `master` branch, since the version I used earlier was missing the `wppus_get_package_info` or `wppus_download_local_package` function (that was available in the docs).

I'll try the 1.14.16 release.

You stated that version 2 and onward are not compatible with the current releases. That doesn't mean that we can't update/migrate to a newer version?

**Comment by froger-me** [comment]
There has not been significant updates (aside from contribution 8.2 compat) to this project for close to 4 years.
During the past month, I have:

1. merged contributions to ensure we have a stable v1.x compatible with current latest PHP ; a branch will be created upon release of v2 and will accept contribution for maintenance
2. started a v2.x with no upgrade path, given the amount of changes, respecting semver.

Upgrading from v1 to v2 should not be too painful - swapping package update library, existing licenses should still be working, although there may be a database column to add ; other than than it's mostly it's option names that differ, and a lot of new added features, so it's a matter of reinstalling and reconfiguring.
But as always, it's worth testing in a staging env before rolling out any critical system in prod.

If time allows (currently writing a WooCommerce integration leveraging all the new APIs), I'll write an upgrade path ; it will still be manual though, not an automatic migration.

**Comment by froger-me** [comment]
Note regarding the errors you found: if you want to speed up the release of 2.x, I very much welcome pull requests :D (provided WP coding standards are fully respected, code formatting and variable naming semantic consistency is preserved, etc etc)

**Comment by froger-me** [comment]
fixed in [e8754e8](https://github.com/froger-me/wp-packages-update-server/commit/e8754e83c36d65217dbc87294ec7a8cb1e13280e)
