### ISSUE TITLE
{feature request] Company and contact information as taxonomy

### ISSUE THREAD

**Issue by claytoncollie** [froger-me/wp-packages-update-server#9]
Hi there. first off, thank you so much for this plugin and that it is open source. I have been using the plugin-update-checker library on a suite of plugins and had building a plugin like this on my roadmap.  I am over the moon that I have found this plugin and really appreciate your hard work. Thank you so much! I was searching for the update-plugin-checker repo on github and this plugin popped up on Google. I was yelling in my office at my coworkers how pumped I was that I found this plugin. Seriously thank you!

I am in the early stages of setting this up and went through the exercise of adding a package. Everything was very straight forward in that respect.  What I could see down the road is that typing in the person's name, email, and company every time will get cumbersome, especially when a single client has 4+ licenses.  I was thinking to make this data entry more efficient that each license could be associated with a taxonomy term that is the contact. And then the contact term holds the name, email, company name, etc. So really just an idea, not a 'request'. 

Thanks so much again. Really appreciate your hard work!

**Comment by froger-me** [comment]
Hi @claytoncollie , thank you for the kind words, and the suggestion!
It is definitely something that would be really useful. At the moment I am focusing on other projects in general and pure maintenance for WPPUS specifically. However, I think it is possible to create a companion plugin that pre-fills the values of the form based on a taxonomy term, in a non-disruptive manner:
- on page load, load a javascript that manipulate the DOM to add taxonomy term selection markup to the license form
- when the license form is visible and the user interacts with a call to action, fire an XHR to get the contact info and pre-fill the form

This way, you'd be able to achieve what you're looking for, and keeping it contained would ensure that if, down the line, the feature is added to core, you'd just have to disable your plugin, or at worst migrate the terms to a new taxonomy.

**Comment by froger-me** [comment]
Closing the issue.
